Create discord-release-msg.yml
SideStore/SideStore pull request #436
Opened 2023-08-05 23:28 UTC by WesleyBryie

Sends message to Discord server by webhook.

### Changes

- added discord-release-msg

### Todo before merge

(or after): add discord webhook stuff

2023-08-05 23:47 UTC, WesleyBryie commented
> Builds for this Pull Request are available at [SideStore-0.5.0-pr.436+17f1f64.ipa](https://github.com/SideStore/SideStore/suites/14853465557/artifacts/845825111) [SideStore-0.5.0-pr.436+17f1f64-dSYM](https://github.com/SideStore/SideStore/suites/14853465557/artifacts/845825112) Have a nice day.

ah yes, _**fresh ipa.**_

2023-08-06 01:44 UTC, naturecodevoid commented
We'll want to fork the action to create forum posts, which probably isn't possible with a webhook

2023-08-06 02:19 UTC, WesleyBryie commented
Would like to point out that this all also applies to:

https://github.com/SideStore/SideServer-for-Linux/pull/7
and
https://github.com/SideStore/SideServer-Windows/pull/18

2024-02-01 01:35 UTC, JoeMatt approved these changes

2024-02-12 01:27 UTC, SternXD requested changes
I would like this addressed before I give my approval.

2024-02-12 01:27 UTC, SternXD commented on .github/workflows/discord-release-msg.yml
> +    runs-on: ubuntu-18.04
Is there a reason you chose Ubuntu 18.04?

2024-02-12 02:37 UTC, WesleyBryie commented
If needed for referenced, the action code is here: [https://github.com/nhevia/discord-styled-releases.](https://github.com/nhevia/discord-styled-releases)

2024-04-02 22:41 UTC, WesleyBryie commented
https://github.com/discord/discord-api-docs/discussions/5610 This is relevant. If we make/find a bot or whatever that could do this automatically, that would make things greatly easier with the current setup.

2024-06-23 03:24 UTC, JoeMatt approved these changes

2024-06-23 03:47 UTC, WesleyBryie commented
Just wanna point out, the current discord setup isn't compatible with this workflow. Further discussion is needed, we need to decide if we want to change the server or make a bot/webhook.

2024-08-15 00:32 UTC, Spidy123222 commented
> Just wanna point out, the current discord setup isn't compatible with this workflow. Further discussion is needed, we need to decide if we want to change the server or make a bot/webhook.

Should we keep this open?

2024-08-15 00:42 UTC, polymo1 commented
> Should we keep this open?

Honestly, I don't think it needs to stay open. We haven't discussed it any, and it would require something probably with SideBot, which doesn't need an action change in the repo.

Closing for not planned.

2024-08-15 00:42 UTC, closed without merging