Change Patreon screen
SideStore/SideStore pull request #62
Opened 2022-09-01 18:13 UTC by bogotesr

Settings page now shows as "Patreon" rather than "Join the beta" under that has a different description. The page itself now links to the JITStreamer Patreon.

**typos have been corrected since the screenshot was taken.**

![IMG_FA2006DDE46C-1](https://user-images.githubusercontent.com/71040782/187983784-5fbbb50d-b1f3-425f-b3d4-97ea8e841135.jpeg)

![IMG_FA2006DDE46C-2](https://user-images.githubusercontent.com/71040782/187983827-6e3d1d10-af1b-41bc-a5f1-d35b471a6144.jpeg)

2022-09-02 10:27 UTC, SternXD commented
I don't see a problem with this PR other than the typos which you said have been resolved so I see no reason not to merge this. Thoughts anyone?

2022-09-14 02:47 UTC, Spidy123222 commented
> Settings page now shows as "Patreon" rather than "Join the beta" under that has a different description. The page itself now links to the JITStreamer Patreon.
> 
> **typos have been corrected since the screenshot was taken.**
> 
> ![IMG_FA2006DDE46C-1](https://user-images.githubusercontent.com/71040782/187983784-5fbbb50d-b1f3-425f-b3d4-97ea8e841135.jpeg)
> 
> ![IMG_FA2006DDE46C-2](https://user-images.githubusercontent.com/71040782/187983827-6e3d1d10-af1b-41bc-a5f1-d35b471a6144.jpeg)

Could you make it only say SideTeam as it’s a group project, not a solo one. Other than that I’m fine with it excluding typos mentioned that were fixed.

2022-09-14 11:25 UTC, JJTech0130 requested changes
Other than the few things I commented on, it looks good.

2022-09-14 11:25 UTC, JJTech0130 commented on AltStore/Resources/Assets.xcassets/Image.imageset/Contents.json
> +      "filename" : "180 2.png",
What’s up with the naming of these files? If they’re different sizes, why not name them like SideStore-1x.png? And why is the imageset just called “Image”?

2022-09-14 11:25 UTC, JJTech0130 commented on AltStore/Resources/Assets.xcassets/jackson.imageset/Contents.json
> +      "filename" : "unnamed 2.png",
Same thing as above, would be good to have more descriptive names

2022-09-14 11:25 UTC, JJTech0130 commented on AltStore/Settings/PatreonViewController.swift
> +        //self.collectionView.register(PatronsFooterView.self, forSupplementaryViewOfKind: UICollectionView.elementKindSectionFooter, withReuseIdentifier: "PatronsFooter")
We have Git, no need to comment things out

2022-09-27 20:09 UTC, Spidy123222 commented
This pr works with upstream changes. I'm unsure if we should make the patreon page more broad as singling out one user can have unfair for everyone else that works hard on the project. Would it be fine to just mention SideTeam above only on left side.

2022-11-01 21:12 UTC, jkcoxson commented
Let's get this one merged. I would prefer if y'all didn't use my picture (it's a team project) but then I think this is fine.

2022-11-06 09:02 UTC, Spidy123222 commented
i just fixed merge conflicts will test if anything needs changes

2022-11-06 09:03 UTC, jkcoxson commented
Still not a fan of having my name and picture there

2022-11-08 19:13 UTC, jkcoxson commented
Something is wrong with this PR, it's a duplicate of one that's already been merged. What happened to the Patreon screen changes?

2022-11-14 04:56 UTC, Spidy123222 commented
> Something is wrong with this PR, it's a duplicate of one that's already been merged. What happened to the Patreon screen changes?

Yeah this was discussed in the discord chat apparently after a accidental git revert it managed to get on their develop branch and revert to a merged pr some how.

2022-11-15 00:37 UTC, bogotesr commented
should now be all fixed up

2022-11-15 02:33 UTC, JoeMatt commented
32 commits?

I think this needs a rebase.

I can do it if you want in a few mins.

2022-11-15 02:59 UTC, JoeMatt commented
I can't edit the source of a PR or publish to an outside repo, so I rebased it here.

OP can either update their branch with this or we can replace with this PR.


FYI, commit credits still belong to @bogotesr but there were conflicts with develop that needed to be resolved.

The biggest one is Server.swift is deleted instead of modified as it was removed on dev.

2022-11-16 21:16 UTC, closed without merging